### ISSUE TITLE
Error in the linear independence definition

### ISSUE THREAD

**Issue by ppeigne** [JohnGiorgi/mathematics-for-machine-learning#10]
Hi, 
I think (if I understand linear independence properties well) that there is a mistake at the end of the part dedicated to the linear independence (Week2). 

The conditions you give are for **linear independence and not linear dependence**

```
To drive the point home, we note that the following are true if b3 is linearly dependent to the vectors b1 and b2: 
b3 does not lie in the plane spanned by b1 and b2
b3≠c1b1+c2b2 for any c1, c2∈R
OR, equivalently,
0=c1b1+c2b2+c3b3 implies that c1=c2=c3=0
```

**Comment by JohnGiorgi** [comment]
You are right. Thanks for noticing that! Mind opening a PR with the fix and I will merge straight away?
