### ISSUE TITLE
[label=invalid] Error in definition of vector basis (mathematics-for-machine-learning/docs/linear_algebra)

### ISSUE THREAD

**Issue by madvid** [JohnGiorgi/mathematics-for-machine-learning#11]
Hello JohnGiorgi,
I find a mistake in your very nice document on linear_algebra for ML.

**Path:**  mathematics-for-machine-learning/docs/linear_algebra
**File:** week_1.md 
**section:** operations with vectors
**subsection:** Coordinate systems

There is a mistake in the definition of the 2nd vector constituting the vector basis of the coordinate system:
$$ \hat{j} = \begin{bmatrix} 1 \\ 0 \end{bmatrix}$$
which is the same vector than $\hat{i}$.
j vector should be :
$$ \hat{j} = \begin{bmatrix} 0 \\ 1 \end{bmatrix}$$

**Comment by JohnGiorgi** [comment]
Awesome, thanks for catching that. Mind opening a PR with the fix and I will merge it straight away?
