### ISSUE TITLE
Why notes are available only upto 2nd week of calculus?

### ISSUE THREAD

**Issue by codes-and-stories** [JohnGiorgi/mathematics-for-machine-learning#15]

**Comment by codes-and-stories** [comment]
It's really helpful, please upload the rest.

**Comment by JohnGiorgi** [comment]
Hi @indianbee,

I never got around to finishing the Calculus course. Hopefully I can start it again this summer. If I do, I will upload my notes as I take it. Thanks!

**Comment by codes-and-stories** [comment]
😄 thank you
